// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAggregate() {
  return window['go']['main']['App']['CancelAggregate']();
}

export function CancelAllDownloads() {
  return window['go']['main']['App']['CancelAllDownloads']();
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function FetchReports(arg1, arg2) {
  return window['go']['main']['App']['FetchReports'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectSaveFile() {
  return window['go']['main']['App']['SelectSaveFile']();
}

export function SetConcurrency(arg1) {
  return window['go']['main']['App']['SetConcurrency'](arg1);
}

export function StartAggregate(arg1, arg2) {
  return window['go']['main']['App']['StartAggregate'](arg1, arg2);
}

export function StartDownload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3, arg4, arg5);
}

export function WarmupSession() {
  return window['go']['main']['App']['WarmupSession']();
}
