// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelAggregate():Promise<void>;

export function CancelAllDownloads():Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function FetchReports(arg1:string,arg2:string):Promise<Array<main.CompanyResult>>;

export function SelectDirectory():Promise<string>;

export function SelectSaveFile():Promise<string>;

export function SetConcurrency(arg1:number):Promise<void>;

export function StartAggregate(arg1:string,arg2:string):Promise<void>;

export function StartDownload(arg1:string,arg2:Array<main.Attachment>,arg3:string,arg4:string,arg5:string):Promise<void>;

export function WarmupSession():Promise<void>;
